name: sharing-artifacts-btw-jobs
on: [push]
jobs:
  job1:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          #pip install -r requirements.txt
          #python model.py
          
          echo "## Model Metrics" >> metrics.txt
          cat metrics.txt >> report.md
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-report-artifact
          path: metrics.txt
          
#       - name: 'Echo upload path'
#         run: echo ${{steps.upload.outputs.upload-path}}
  
  job2:
      needs : [ job1 ]
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - uses: actions/checkout@v2
        
        - name: download report artifacts
          uses: actions/download-artifact@v3
          with:
            name: my-report-artifact
        
        - name: 'Echo download path'
          run: echo ${{steps.download.outputs.download-path}}
            
            
        - name: 'Train my model'
          env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cat metrics.txt
            python read_artifact.py
            

        
